### PR TITLE
fix variables.c

### PR DESCRIPTION
**Pull request by sadeem-albir**
Changed the command letters to capital-case to prevent overlapping with VARGET

### CODE REVIEW

**Comment by ohkimur** [comment]
@sadeem-albir Can you explain the problem a bit better?

**Comment by sadeem-albir** [comment]
> @sadeem-albir Can you explain the problem a bit better?

Yes! So the commands 'h' for viewhead and 'c' for clear-stack, etc. are implemented in the program, they get ignored because the program checks for lower-case letters to see if the user is inputting a variable they defined.

**Comment by ohkimur** [comment]
@sadeem-albir Thanks for your contribution.

**Comment by sadeem-albir** [comment]
> @sadeem-albir Thanks for your contribution.
No problem, this is actually my first contribution on Github, and I'm glad it helped. And the exercises helped me a lot in the K&R book when I was having difficulties with exercises. I will check for other merge conflicts that may not have been resolved yet. If there is any further issue, feel free to let me know.

**Pull request merged**
