### PR TITLE
Update reverse.c

### PR DESCRIPTION
**Pull request by sadeem-albir**
Reset the static variables after the reversing process was complete so the reverse function can be used more than once without issue.

### CODE REVIEW

**Review by ohkimur — APPROVED** [review]

**Comment by ohkimur** [comment]
@sadeem-albir Can you fix the build for this one?

**Review by ohkimur — CHANGES_REQUESTED** [review]
@sadeem-albir Fix the build!

**Comment by sadeem-albir** [comment]
> @sadeem-albir Can you fix the build for this one?

This is odd. I will try to check what the issue with it is.

**Comment by sadeem-albir** [comment]
@ohkimur Ok I saw the issue. I need to stop mixing up between s and str a lot

**Review by ohkimur — APPROVED** [review]
Thanks for contributing!

**Comment by sadeem-albir** [comment]
@ohkimur anytime :)

**Pull request merged**
